package org.yournamehere.client;
// Generated 23.3.2012 21:24:48 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.*;

/**
 * Akcie generated by hbm2java
 */
@Entity
@Table(name="AKCIE"
    ,schema="MBSYSTEM"
)
public class Akcie  implements java.io.Serializable {


     private int id;
     private Integer cislo;
     private Long cisloAkcie;
     private String serie;
     private String typ;
     private BigDecimal hodnota;
     private Date datum;
     private String poznamka;
     private byte[] text;

    public Akcie() {
    }

	
    public Akcie(int id) {
        this.id = id;
    }
    public Akcie(int id, Integer cislo, Long cisloAkcie, String serie, String typ, BigDecimal hodnota, Date datum, String poznamka, byte[] text) {
       this.id = id;
       this.cislo = cislo;
       this.cisloAkcie = cisloAkcie;
       this.serie = serie;
       this.typ = typ;
       this.hodnota = hodnota;
       this.datum = datum;
       this.poznamka = poznamka;
       this.text = text;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=9, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="CISLO", precision=9, scale=0)
    public Integer getCislo() {
        return this.cislo;
    }
    
    public void setCislo(Integer cislo) {
        this.cislo = cislo;
    }
    
    @Column(name="CISLO_AKCIE", precision=12, scale=0)
    public Long getCisloAkcie() {
        return this.cisloAkcie;
    }
    
    public void setCisloAkcie(Long cisloAkcie) {
        this.cisloAkcie = cisloAkcie;
    }
    
    @Column(name="SERIE", length=20)
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    
    @Column(name="TYP", length=20)
    public String getTyp() {
        return this.typ;
    }
    
    public void setTyp(String typ) {
        this.typ = typ;
    }
    
    @Column(name="HODNOTA", precision=12)
    public BigDecimal getHodnota() {
        return this.hodnota;
    }
    
    public void setHodnota(BigDecimal hodnota) {
        this.hodnota = hodnota;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATUM", length=7)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    
    @Lob
    @Column(name="POZNAMKA")
    public String getPoznamka() {
        return this.poznamka;
    }
    
    public void setPoznamka(String poznamka) {
        this.poznamka = poznamka;
    }
    
    @Lob
    @Column(name="TEXT")
    public byte[] getText() {
        return this.text;
    }
    
    public void setText(byte[] text) {
        this.text = text;
    }




}


