package org.yournamehere.client;
// Generated 24.3.2012 10:30:18 by Hibernate Tools 3.2.1.GA


import java.sql.Clob;
import java.util.Date;
import javax.persistence.*;
import org.hibernate.annotations.GenericGenerator;

/**
 * ZalobyZpravy generated by hbm2java
 */
@Entity
@Table(name="ZALOBY_ZPRAVY"
    ,schema="MBSYSTEM"
)
@SequenceGenerator(name="NEWID", sequenceName="NEWID")
public class ZalobyZpravy  implements java.io.Serializable {


     private int id;
     private String refKod;
     private Date datumStazeni;
     private String typZpravy;
     private String predmet;
     private Date datumOdeslani;
     private String odesilatel;
     private String idZpravy;
     private String ucet;
     private String varSymb;
     private String podaniDoruceneDatum;
     private String bezneCislo;
     private String podaniOverenoDatum;
     private Short zaslanychPriloh;
     private String zpusobPodani;
     private String podpisCertifPlatny;
     private String soud;
     private String typFormulare;
     private String spisovaZnacka;
     private String keZpracovani;
     private String telo;

    public ZalobyZpravy() {
    }

	
    public ZalobyZpravy(int id) {
        this.id = id;
    }
    public ZalobyZpravy(int id, String refKod, Date datumStazeni, String typZpravy, String predmet, Date datumOdeslani, String odesilatel, String idZpravy, String ucet, String varSymb, String podaniDoruceneDatum, String bezneCislo, String podaniOverenoDatum, Short zaslanychPriloh, String zpusobPodani, String podpisCertifPlatny, String soud, String typFormulare, String spisovaZnacka, String keZpracovani, String telo) {
       this.id = id;
       this.refKod = refKod;
       this.datumStazeni = datumStazeni;
       this.typZpravy = typZpravy;
       this.predmet = predmet;
       this.datumOdeslani = datumOdeslani;
       this.odesilatel = odesilatel;
       this.idZpravy = idZpravy;
       this.ucet = ucet;
       this.varSymb = varSymb;
       this.podaniDoruceneDatum = podaniDoruceneDatum;
       this.bezneCislo = bezneCislo;
       this.podaniOverenoDatum = podaniOverenoDatum;
       this.zaslanychPriloh = zaslanychPriloh;
       this.zpusobPodani = zpusobPodani;
       this.podpisCertifPlatny = podpisCertifPlatny;
       this.soud = soud;
       this.typFormulare = typFormulare;
       this.spisovaZnacka = spisovaZnacka;
       this.keZpracovani = keZpracovani;
       this.telo = telo;
    }
   
    @Id 
    @Column(name="ID", unique=true, nullable=false, precision=9, scale=0)
    @GeneratedValue(strategy=GenerationType.SEQUENCE, generator="NEWID")
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="REF_KOD", length=240)
    public String getRefKod() {
        return this.refKod;
    }
    
    public void setRefKod(String refKod) {
        this.refKod = refKod;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_STAZENI", length=7)
    public Date getDatumStazeni() {
        return this.datumStazeni;
    }
    
    public void setDatumStazeni(Date datumStazeni) {
        this.datumStazeni = datumStazeni;
    }
    
    @Column(name="TYP_ZPRAVY", length=120)
    public String getTypZpravy() {
        return this.typZpravy;
    }
    
    public void setTypZpravy(String typZpravy) {
        this.typZpravy = typZpravy;
    }
    
    @Column(name="PREDMET", length=1000)
    public String getPredmet() {
        return this.predmet;
    }
    
    public void setPredmet(String predmet) {
        this.predmet = predmet;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_ODESLANI", length=7)
    public Date getDatumOdeslani() {
        return this.datumOdeslani;
    }
    
    public void setDatumOdeslani(Date datumOdeslani) {
        this.datumOdeslani = datumOdeslani;
    }
    
    @Column(name="ODESILATEL", length=240)
    public String getOdesilatel() {
        return this.odesilatel;
    }
    
    public void setOdesilatel(String odesilatel) {
        this.odesilatel = odesilatel;
    }
    
    @Column(name="ID_ZPRAVY", length=1000)
    public String getIdZpravy() {
        return this.idZpravy;
    }
    
    public void setIdZpravy(String idZpravy) {
        this.idZpravy = idZpravy;
    }
    
    @Column(name="UCET", length=120)
    public String getUcet() {
        return this.ucet;
    }
    
    public void setUcet(String ucet) {
        this.ucet = ucet;
    }
    
    @Column(name="VAR_SYMB", length=120)
    public String getVarSymb() {
        return this.varSymb;
    }
    
    public void setVarSymb(String varSymb) {
        this.varSymb = varSymb;
    }
    
    @Column(name="PODANI_DORUCENE_DATUM", length=120)
    public String getPodaniDoruceneDatum() {
        return this.podaniDoruceneDatum;
    }
    
    public void setPodaniDoruceneDatum(String podaniDoruceneDatum) {
        this.podaniDoruceneDatum = podaniDoruceneDatum;
    }
    
    @Column(name="BEZNE_CISLO", length=120)
    public String getBezneCislo() {
        return this.bezneCislo;
    }
    
    public void setBezneCislo(String bezneCislo) {
        this.bezneCislo = bezneCislo;
    }
    
    @Column(name="PODANI_OVERENO_DATUM", length=120)
    public String getPodaniOverenoDatum() {
        return this.podaniOverenoDatum;
    }
    
    public void setPodaniOverenoDatum(String podaniOverenoDatum) {
        this.podaniOverenoDatum = podaniOverenoDatum;
    }
    
    @Column(name="ZASLANYCH_PRILOH", precision=4, scale=0)
    public Short getZaslanychPriloh() {
        return this.zaslanychPriloh;
    }
    
    public void setZaslanychPriloh(Short zaslanychPriloh) {
        this.zaslanychPriloh = zaslanychPriloh;
    }
    
    @Column(name="ZPUSOB_PODANI", length=120)
    public String getZpusobPodani() {
        return this.zpusobPodani;
    }
    
    public void setZpusobPodani(String zpusobPodani) {
        this.zpusobPodani = zpusobPodani;
    }
    
    @Column(name="PODPIS_CERTIF_PLATNY", length=120)
    public String getPodpisCertifPlatny() {
        return this.podpisCertifPlatny;
    }
    
    public void setPodpisCertifPlatny(String podpisCertifPlatny) {
        this.podpisCertifPlatny = podpisCertifPlatny;
    }
    
    @Column(name="SOUD", length=240)
    public String getSoud() {
        return this.soud;
    }
    
    public void setSoud(String soud) {
        this.soud = soud;
    }
    
    @Column(name="TYP_FORMULARE", length=120)
    public String getTypFormulare() {
        return this.typFormulare;
    }
    
    public void setTypFormulare(String typFormulare) {
        this.typFormulare = typFormulare;
    }
    
    @Column(name="SPISOVA_ZNACKA", length=120)
    public String getSpisovaZnacka() {
        return this.spisovaZnacka;
    }
    
    public void setSpisovaZnacka(String spisovaZnacka) {
        this.spisovaZnacka = spisovaZnacka;
    }
    
    @Column(name="KE_ZPRACOVANI", length=120)
    public String getKeZpracovani() {
        return this.keZpracovani;
    }
    
    public void setKeZpracovani(String keZpracovani) {
        this.keZpracovani = keZpracovani;
    }
    
    @Lob
    @Column(name="TELO")
    public String getTelo() {
        return this.telo;
    }
    
    public void setTelo(String telo) {
        this.telo = telo;
    }




}


